### ISSUE TITLE
🌟 [feat] Payment 도메인

### ISSUE THREAD

**Issue by Soeng-dev** [HuijinKang/food-order-management-service#10]
**🌟 Issue : Feature**
Feature 작업 사항을 작성해주세요

**Description**
작업사항에 대한 설명을 작성해주세요

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 결제 조회 api
- [x] 결제 목록 조회 api
- [x] 결제 수동 생성 api
- [x] 결제 정보 변경 api
- [x] 결제 취소 api

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
