### ISSUE TITLE
🌟 [feat] User도메인 개발

### ISSUE THREAD

**Issue by rua0704** [HuijinKang/food-order-management-service#13]
**🌟 Issue : Feature**
User 도메인 개
**Description**

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 사용자 조회 API
- [x] 회원정보 수정 API
- [x] 사용자 권한 수정 API
- [x] 회원탈퇴 API

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
