### ISSUE TITLE
🌟 [feat] Category 도메인 개발 

### ISSUE THREAD

**Issue by HuijinKang** [HuijinKang/food-order-management-service#28]
**🌟 Issue : Feature**
Category 도메인 API 개발

**Description**
작업사항에 대한 설명을 작성해주세요

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 카테고리 조회 API
- [x] 카테고리명으로 스토어 목록 조회 API
- [x] 카테고리 등록 API
- [x] 카테고리 수정 API
- [x] 카테고리 삭제 API

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
