### ISSUE TITLE
🌟 [feat] Store도메인 개발

### ISSUE THREAD

**Issue by HuijinKang** [HuijinKang/food-order-management-service#8]
**🌟 Issue : Feature**
Store도메인 개발

**Todo**
- [x] 주문 가능 가게 조회 api
- [x] 가게 단건 조회 api
- [x] 가게 검색 api
- [x] 가게 등록 api
- [x] 가게 정보 수정 api
- [x] 가게 삭제 api
